import json

# Each question: (num, text, [options], correct  -> int index OR list of ints for multi-select, explanation)
Q = [
(1,"The Cross consists of two components. They are…",
 ["Defeat and death","Joy and winning","Resurrection and joy","Resurrection and enduring hardship"],3,
 "The Cross holds together enduring hardship (the crucifixion) and resurrection (the victory) — suffering and glory together."),
(2,"Where do we learn why Christ endured a humiliating death for us?",
 ["Romans 6:23","Colossians 1:24","Hebrews 12:2","Romans 8:37"],2,
 "Hebrews 12:2 — \"for the joy set before Him, He endured the cross.\""),
(3,"Was the Cross a historical accident?",
 ["Yes","No, God planned it for Adam","No, God planned it for His Son","No, God planned it for us"],3,
 "The Cross was God's plan from the beginning for the salvation of humanity — for us."),
(4,"If God simply forgave the sins, what is the result?",
 ["God's justice would not stand","It would be okay to happen.","We would not have any consequences to our sins","We would never hurt one another."],0,
 "Forgiveness without payment for sin would mean God's justice does not stand."),
(5,"When Adam sinned, God had a Divine Dilemma: that He loved humanity but He had also warned them what would happen apart from Him. Where is the solution explained?",
 ["\u201cThe sting of death is sin, and the strength of sin is the law.\u201d (1 Corinthians 15:56)",
  "\u201cMercy and truth have met together; Righteousness and peace have kissed.\u201d (Psalm 85:10)",
  "\u201cfor all have sinned and fall short of the glory of God.\u201d (Romans 3:23)",
  "\u201cBlessed are the merciful, for they shall obtain mercy.\u201d (Matthew 5:7)"],1,
 "Psalm 85:10 pictures mercy and truth, righteousness and peace, meeting — God's love and justice reconciled in the Cross."),
(6,"Our Lord Jesus Christ is our Redeemer. For this to be true, why did He have to be the Creator?",
 ["To renew our corrupted nature and recreate it a second time.","Because Adam tried to create himself into a god","Because He had to be powerful","Because the one who sinned (Adam) was not a creator"],0,
 "Only the Creator can recreate/renew a corrupted nature — redemption requires re-creation."),
(7,"When we make the sign of the Cross over our bodies, why do we sign from the left shoulder to the right shoulder when declaring \u201cHoly Spirit.\u201d",
 ["We read left to right","Christ is seated at the right hand of God","The Holy Spirit brings us from darkness (\u201cleft\u201d) to light (\u201cright\u201d)","We're mirroring when Abouna blesses the congregation"],2,
 "Left to right symbolizes the Spirit moving us from darkness into light."),
(8,"What is the central theme of Hebrews 12:2 and 1 Peter 2:24?",
 ["There is joy in suffering","God loves the Jewish people","Our sins caused pain","Christ personally endured for us and died for us."],3,
 "Both verses center on Christ personally bearing our suffering and sin."),
(9,"What can we learn from Galatians 3:13?",
 ["Curses came from the law","We inherited Adam's curse","Death was our curse, and Christ took it for us","Cursed things hang on trees, and so do we"],2,
 "\u201cChrist redeemed us from the curse of the law, having become a curse for us.\u201d"),
(10,"The death we deserve is four-fold, and Christ conquered them all for us. What is the difference between spiritual death and mortal death?",
 ["Spiritual death is banishment into a fallen realm. Mortal death is the corruption of our nature.",
  "Spiritual death is a separation from God. Mortal death is being subject to a corrupt realm.",
  "Spiritual death is a corruption of our nature. Mortal death is eternal destruction.",
  "Spiritual death is a separation from God. Mortal death is when our physical bodies no longer have a heartbeat."],3,
 "Spiritual death = separation from God; mortal death = subjection to a fallen, corrupt realm."),
(11,"St. Athanasius gives us insight into the Cross. What does he say about the spiritual meaning of Christ hanging above the earth?",
 ["That Christ might draw us up to Himself","To represent that He came from heaven","Roman crucifixions were always done this way","So everyone would see that He really died"],0,
 "St. Athanasius: Christ was lifted up so that He might draw all people to Himself (cf. John 12:32)."),
(12,"This year marks the 1700th anniversary of what?",
 ["The Council of Nicea","The dedication of the Church of the Resurrection in Jerusalem","The discovery of the Cross by Queen Helen","The departure of St. Athanasius"],2,
 "St. Helena's discovery of the True Cross is traditionally dated to 326 AD — 1700 years before 2026."),
(13,"Sometimes God allows us to go through trials to keep us from falling into future sins. Match this type of trial with the corresponding example.",
 ["Trial of Protection: St. Paul","Trial of Protection: Abraham","Trial of Purification: the Prodigal Son","Trial of Repentance: Job"],0,
 "Abraham's trials are classic examples of God's protective testing."),
(14,"What do the Cross and Acts 5:41 have in common?",
 ["They refer to the same people","Joy from tribulation","Suffering due to sin is helpful","We will always have peace"],1,
 "Acts 5:41 — the apostles rejoiced to suffer shame for His name, echoing the joy found through the Cross."),
(15,"Where do we hear of death being a step toward a realm with the saints?",
 ["The Litany of the Traveler","The Litany of the Sick","The Litany of the Oblations","The Litany of the Departed"],3,
 "The Litany of the Departed speaks of death as passage into the realm of the saints."),
(16,"Where is Colosse today?",
 ["Israel","Turkey","Rome","Greece"],1,
 "Colosse was located in Asia Minor, modern-day Turkey."),
(17,"What is the purpose of this epistle?",
 ["To confront false teachings in the church established by St. Paul",
  "To confront false teachings in the church when St. Paul was consulted by Epaphras",
  "To define the components of the Church","To challenge the Church to grow"],1,
 "St. Paul never visited Colosse himself; Epaphras founded the church and consulted Paul about the false teachings there."),
(18,"Ephesians and Colossians are complementary. Why?",
 ["They each discuss the Church from different angles","They both reveal St. Paul's suffering in prison",
  "They each applaud their respective cities for their faith","They both discuss Christ as the Head, and we are members of His Body"],3,
 "Both epistles center on Christ as Head of the Church, His Body."),
(19,"What is the purpose of the opening two verses?",
 ["To introduce a new topic","To describe in detail the spiritual significance of grace",
  "To establish the source of these teachings and bless the people","To establish St. Paul as the originator of these ideas"],2,
 "Paul's greetings establish his apostolic authority as the source, and bless the recipients."),
(20,"Hebrews 12:2 says \u201cfor the joy set before Him, He endured the Cross.\u201d How does this idea appear in Colossians 1:3-5?",
 ["His Love for us is why He endured","Hope is what allows us to remain faithful through pain",
  "Faith in Christ Jesus is the most important thing","We are thankful for Christ's sacrifice"],1,
 "Colossians 1:3-5 links faith and love to the hope laid up in heaven — hope sustains us through hardship, as joy sustained Christ."),
(21,"What did Colosse hear about before from Epaphras?",
 ["Resurrection and faith","Love and charity","Glory and thanksgiving","Forgiveness and glory"],3,
 "Col 1:4,8 — Epaphras reported their faith in Christ and their love for the saints."),
(22,"Which of the Colossians' viewpoints did St. Paul try to redirect?",
 ["Salvation is only for the Jews","Jesus is not the Messiah","Love is the only important thing needed for a Christian life","The Trinity is a polytheistic concept"],2,
 "Paul redirects an incomplete view of faith by insisting knowledge (gnosis) must be joined with active good works (praxis), not love/feeling alone."),
(23,"Which verse demonstrates what has come of Epaphras' teaching?",
 ["\u201cYou are the light of the world. A city that is set on a hill cannot be hidden.\u201d (Matt 5:14)",
  "\u201cthere is joy in the presence of the angels of God over one sinner who repents.\u201d (Luke 15:10)",
  "\u201cEvery branch that bears fruit He prunes, that it may bear more fruit.\u201d (John 15:2)",
  "\u201cFirst remove the plank from your own eye...\u201d (Matthew 7:5)"],2,
 "Colossians 1:6 speaks of the gospel bearing fruit among them, echoing the fruit-bearing imagery of John 15:2."),
(24,"Why does St. Paul commend Colosse?",
 ["They loved everybody, slave and free, equally","They spread new churches across the country",
  "They really understood the Resurrection","They heard the teachings of Christ, experienced them, and became new"],3,
 "They heard the word, understood the grace of God in truth, and it bore fruit and grew among them (Col 1:6)."),
(25,"What can we learn from the labor of Epaphras?",
 ["Even if you just clean up something off the floor, but you do it for the glory of God, He will remember it",
  "We should study the Gospel so that we can tell others","It's ok if people don't recognize our efforts","Wisdom is needed to speak with unbelievers"],0,
 "Epaphras's faithful, often unseen labor is remembered and honored by God."),
(26,"In the Hebrew language, there is one combined word for the concept of hearing and the concept of obeying: \u201cshema.\u201d In Deuteronomy 6:4-5, the Shema instructions are to \u201cHear... and love.\u201d What are St. Paul's analogous instructions?",
 ["Listening and praying","Wisdom and understanding","Loving and serving","Praising and worshiping"],1,
 "Colossians 1:9-10 prays for knowledge that leads to a life fully pleasing to the Lord — loving and serving in every good work."),
(27,"Some people say \u201cI understand Christian morals theoretically.\u201d What would St. Paul think about this?",
 ["That's all you need to do","That's not enough","You need to understand deeper","That's a good start, now let's put it into action"],1,
 "Theoretical knowledge (gnosis) alone is not enough — it must lead to action (praxis)."),
(28,"What does the Greek word Praxis mean?",
 ["Praise","Gospel","Action","Prayer"],2,"Praxis = action."),
(29,"What does the Greek word Gnosis mean?",
 ["Gospel","Generosity","Action","Knowledge"],3,"Gnosis = knowledge."),
(30,"What do the Gnostics believe?",
 ["God is understood through a hidden knowledge, not through Scripture, tradition, or doctrine",
  "Non-Jews must follow the Torah Law to be considered Christian",
  "Jesus is the Messiah who was incarnate, crucified, resurrected, and ascended to heaven","The Gnostics are atheist"],0,
 "Gnosticism claims God is reached through secret, hidden knowledge rather than Scripture and apostolic teaching."),
(31,"Which verse explains how the Holy Spirit teaches us in the knowledge of God every day?",
 ["John 14:26","Matthew 6:19","Luke 19:38","Mark 12:43"],0,
 "John 14:26 — the Holy Spirit \u201cwill teach you all things.\u201d"),
(32,"Who intercedes for us when we don't know what to pray about (Romans 8)?",
 ["St. Mary","Abouna","The Holy Spirit","No one"],2,
 "Romans 8:26 — the Spirit intercedes for us with groanings too deep for words."),
(33,"How are we strengthened according to His glorious power?",
 ["By allowing God to do everything","By working synergistically with God",
  "By doing everything according to what we think is best","By planning out every detail of our lives"],1,
 "We are strengthened as we cooperate (work synergistically) with God's grace."),
(34,"Which example is a \u201cdaily life\u201d situation that demonstrates our choice to walk with God or not?",
 ["Another student offered you the answers to an upcoming final exam and you chose not to take it, as it is cheating.",
  "You were asked to introduce the Bishop at a council meeting","You represent all the Christian organizations on your school board","Your senator uses your name to tilt the ballot results"],0,
 "Choosing not to cheat is a concrete daily choice to walk with God."),
(35,"Who said \u201cGod, who created us without us, cannot save us without us.\u201d",
 ["St. Paul","St. Peter","St. Antony","St. Augustine"],3,
 "This well-known statement is attributed to St. Augustine."),
(36,"What is the point of the quote in the previous question?",
 ["God needed us to die on the Cross too","God wants us to participate in working out our salvation (Philippians 2:12)",
  "God shouldn't have created us because we would mess up","God created us in order to save us"],1,
 "Salvation involves our willing participation — \u201cwork out your own salvation\u201d (Phil 2:12)."),
(37,"St. John Chrysostom says \u201cGod not only has given the honor but also made us strong enough to receive it.\u201d What words of St. Paul is he referencing?",
 ["\u201cDelivered us from the power of darkness\u201d (1:13)","\u201cWe have redemption through His blood\u201d (1:14)",
  "\u201cStrengthened with all might, according to His glorious power\u201d (1:11)","\u201cQualified us to be partakers of the inheritance\u201d (1:12)"],3,
 "Chrysostom is commenting on Colossians 1:11 — God strengthens us to bear the honor He gives."),
(38,"Which story is a type of deliverance from darkness, toward a new kingdom?",
 ["The Israelite exodus from Egypt","Adam and Eve banished from Eden","The prodigal son leaving for a new land","The Holy Family's flight to Egypt","Christ defeated the devil, but people still go to Hades"],0,
 "The Exodus from Egypt (bondage/darkness) to the Promised Land (kingdom) is the classic type."),
(39,"What does the Son of His Love mean?",
 ["The only one He loves","The one He loves most","His Beloved Son","His only Son"],2,
 "\u201cThe Son of His love\u201d simply means His Beloved Son."),
(40,"The Colossians were under many false beliefs, including that salvation is possible through the Father alone, without Jesus Christ. John 14:6 addresses this. Which verse(s) in chapter 1 of Colossians does St. Paul use to help correct their understanding?",
 ["Verses 9-10","Verses 12-13","Verse 15","Verse 17"],2,
 "Colossians 1:15 — Christ is \u201cthe image of the invisible God\u201d; we only truly see/know the Father through Him."),
(41,"Sometimes people take verses out of context to say that Christ is not God. For example, \u201cMy Father is greater than I\u201d (John 14:28). What would St. Paul say to those people?",
 ["God, who we cannot see, we now can see through the person of Christ","The Father and the Son are two different gods",
  "Christ is less than the Father, but still God","God taking flesh was scandalous"],0,
 "Colossians 1:15 shows Christ reveals the unseen God, not that He is a lesser God."),
(42,"Which verse addresses the concern from the previous question?",
 ["Ephesians 6:18","1 Timothy 3:16","Mark 11:23","Revelation 3:21"],1,
 "1 Timothy 3:16 — \u201cGod was manifested in the flesh.\u201d"),
(43,"Christ used his physical touch to heal many on earth. Why is this possible?",
 ["God the Father can touch humans physically","A human man can heal by a touch",
  "The Incarnate Word has both flesh to touch and power to heal","It was a miracle"],2,
 "Christ's dual nature — true flesh and divine power — makes physical healing through touch possible."),
(44,"\u201cSo God created mankind in His own image\u201d (Genesis 1:27). But Colossians tells us Christ is the image of God. How can this be?",
 ["When Christ took a body, He molded it to look like Adam so He would share the same look as man",
  "Christ was never created. He is the original image, and we are His copies","We are gods like Christ is God","Christ's image and our image (of God) are the same"],1,
 "Christ is the eternal, uncreated image of God; humanity was made according to that image."),
(45,"\u201cBlood\u201d has many biblical references. What does St. Paul equate it to?",
 ["The life of a person","The evidence of a sacrifice","The representation of human flesh","The forgiveness of sins"],3,
 "Biblically, blood represents the life of a person (Leviticus 17:11)."),
(46,"How do Gnostics use the word \u201cemanate\u201d?",
 ["The Son depicts the glory of the Father","The Son is the same essence as the Father",
  "The Son is not the same essence as the Father","The Son is seen and the Father is not seen"],2,
 "Gnostics wrongly taught the Son as a lesser \u2018emanation,\u2019 not of the same essence as the Father."),
(47,"What does the Greek word \u201cikon\u201d mean?",
 ["Image","Twin","Reflection","Opposite"],0,"Ikon = image."),
(48,"Why does St. Paul use the word \u201cfirstborn\u201d to describe Christ?",
 ["Because the Son is begotten of the Father, not created.","Because Christ was the first born (and only) child of St. Mary",
  "Because Christ was created from before Adam","Born and created mean the same thing in this context"],0,
 "\u201cFirstborn\u201d expresses that the Son is eternally begotten, not created."),
(49,"How can we recognize Christ as the image of God?",
 ["When we see Christ, we understand what the Father looks like physically","When we see the Law, we see Christ, who fulfilled it as the image of the Father",
  "No one has seen the Father, so we can't recognize His image","When we see Christ, we get a rudimentary glimpse of what the Father is like"],3,
 "Since no one has seen the Father directly, Christ gives us a true (if partial, human-comprehensible) glimpse of Him."),
(50,"Exodus 40 tells the detailed description of God's instructions to Moses about how to set up the tabernacle: \u201cMoses finished the work. Then the cloud covered the tabernacle of meeting, and the glory of the Lord filled the tabernacle.\u201d Where in Colossians do we see this theme of God dwelling with His people?",
 ["\u201cBeing fruitful in every good work\u201d","\u201cGiving thanks to the Father\u201d","\u201cHe has delivered us from the power of darkness\u201d","\u201cAll things were created through Him and for Him.\u201d"],3,
 "As all things were created through and for Him, Christ's presence fills creation the way God's glory filled the tabernacle."),
(51,"Which chapter echoes the ideas in Colossians 1:16?",
 ["Matthew 2","John 1","John 6","Mark 16"],1,
 "John 1:3 — \u201cAll things were made through Him\u201d parallels Colossians 1:16."),
(52,"\u201cAll things were created through Him.\u201d What can humans claim as our own doing?",
 ["Nothing, God created everything","Good deeds","Sin","Tithing"],2,
 "Since all things were created through Christ, nothing is ultimately of our own making."),
(53,"If a potter molds a vase from clay, the vase serves the purposes of the potter. Similarly, if God created us…",
 ["He gave us free will to please ourselves","We are not our own masters, but His servants",
  "He gave us free will so we would give free will to others","We are our own masters"],1,
 "As the potter's vase serves the potter, we belong to God and serve His purposes, not our own."),
(54,"Lazarus was raised from the dead, but eventually died. Christ raised himself from the dead, and continued living. This is why Saint Paul says…",
 ["\u201cfirst born from the dead\u201d","\u201cin Him all things consist\u201d","\u201cHe is the image of the invisible God\u201d","\u201cIn Him all the fullness should dwell\u201d"],0,
 "Christ is the firstborn from the dead — the first to rise and never die again."),
(55,"Christ created and rules over principalities and powers. Where else do we hear of such ranks?",
 ["James 1:5","Romans 12:1","Ephesians 6:12","Philippians 3:7"],2,
 "Ephesians 6:12 names principalities and powers among the spiritual ranks Christ rules over."),
(56,"Fill in the blank from St. John Chrysostom: \u201cThen having spoken of His dignity, [Paul] also proceeds to speak of His love for humanity. \u2018He is,\u2019 he says, \u2018the head of ________.\u2019...\u201d",
 ["the world","those who have fallen asleep","Creation","the body, the church"],3,
 "Chrysostom highlights Christ as \u201cthe head of the body, the church\u201d — His friendliness to us."),
(57,"What does preeminence mean here?",
 ["Christ was the first bishop","Christ was the first person to rise from the dead",
  "As the Creator, everything that exists belongs to Christ","As the Head, Christ is our example of how to live"],2,
 "Preeminence: as Creator of all, Christ has first place over everything that exists."),
(58,"We don't worship anyone except for Christ. Where do we read an example of what not to do?",
 ["Revelation 22:8-9","Deuteronomy 6:5","Hebrews 1:6","Isaiah 25:1"],0,
 "Revelation 22:8-9 — John is told not to worship the angel, only God."),
(59,"If you inherit a broken car, it doesn't get fixed by driving around and ignoring it. How do we understand this spiritually?",
 ["Adam was our head, and we can live by being different than him","Christ is our head, and we can live apart from Him",
  "We cannot live by Adam's dead body. We need adoption into Christ's renewed body","Christ is the Head of the Church"],2,
 "We can't fix our fallen (Adamic) nature by ignoring it — we need to be adopted into Christ's renewed Body."),
(60,"We were members of a dead body, with Adam as the head. What changed?",
 ["John 6:49","Romans 8:15","Joshua 5:6","Matthew 23:30"],1,
 "Romans 8:15 — we received the Spirit of adoption, becoming members of Christ's renewed Body."),
(61,"Why can't Jesus just raise everyone like Lazarus? (Hint: Lazarus still died)",
 ["He can, and will","Matthew 10:8","That wouldn't fix the problem of our inherited corrupted nature","Hebrews 11:35"],2,
 "Raising a body like Lazarus's wouldn't heal our inherited corrupted nature — the real problem."),
(62,"What is the solution to the problem in the previous question?",
 ["Christ had to renew our nature (God had to become man)","Adam had to die because he disobeyed God in the garden",
  "We have to die to reconcile for our sin","We have to renew our nature (become god-like)"],0,
 "God had to become man to actually renew human nature from within."),
(63,"St. Athanasius said \u201cGod became man so that man might become like god\u201d. What is the significance of this quote?",
 ["It teaches us joy and kindness","It explains the sacrament of baptism","It shows how and why Christ came","It retells the Exodus story"],2,
 "This famous line from St. Athanasius summarizes the purpose of the Incarnation."),
(64,"Who did it please that in Christ dwelt all the fullness?",
 ["The Colossians","The Christians","The Holy Spirit","The Father"],3,
 "Colossians 1:19 — \u201cit pleased the Father that in Him all the fullness should dwell.\u201d"),
(65,"The Holy Spirit is dwelling in us, but we don't have what Christ has. According to Colossians 1:19, Christ is…",
 ["the Trinity","the fullness of God","a prophet","a king"],1,
 "Christ uniquely holds \u201call the fullness\u201d of God dwelling bodily in Him (cf. Col 2:9)."),
(66,"John 1:16 says \u201cAnd of His fullness we have all received.\u201d What does the word \u201cof\u201d signify here?",
 ["We are fully God and fully human","We have divine nature","Every good thing we have comes of Christ","We are full of goodness like Christ"],2,
 "Everything good we receive flows out from Christ's fullness."),
(67,"Colossians 1:20 says \u201cby Him\u201d twice. Who is Him?",
 ["The Father","The Son","The Holy Spirit","The Trinity"],1,
 "Both instances of \u201cby Him\u201d refer to the Son, through whom reconciliation happens."),
(68,"The term \u201creconcile\u201d implies what status change between two people?",
 ["Strangers -> united","Strangers -> strangers","United -> united","United -> strangers"],0,
 "Reconciliation moves estranged parties into unity."),
(69,"How do we become sacramentally reconciled in the body of His flesh?",
 ["Charity","Forgiveness","Praising","The Eucharist"],3,
 "The Eucharist is our sacramental participation in Christ's body, our means of reconciliation."),
(70,"St. Paul instructs us to \u201ccontinue in the faith.\u201d Where does he say to get this inspiration?",
 ["The words of sermons","The faith of others","The love of the church","The hope of the gospel"],3,
 "Colossians 1:23 — grounded and steadfast, not moved from the hope of the gospel."),
(71,"Colossians 1:9 and 2:2 both encourage the practical use of knowledge. What is this called?",
 ["Patience","Gentleness","Understanding","Truth"],2,
 "Both passages pair knowledge with understanding — knowledge put to practical use."),
(72,"What is our source of persistence to remain united with someone, even when they've wronged us?",
 ["Joy","Peace","Hope","Love"],3,
 "Colossians 3:14 — love is the bond that holds everything together in unity."),
(73,"Where does this fruit from the previous question come from?",
 ["Scripture reading","The Holy Spirit","It's naturally within us","Practice"],1,
 "Love is a fruit of the Holy Spirit (Galatians 5:22)."),
(74,"Gnostics believe knowledge of God is obtained though hidden, mysterious means. St. Paul wishes to clarify the understanding of the Colossians by giving a name to that mystery. He argues that knowing God can only be accomplished.",
 ["By pure academic study","Through repetitive rituals","Through His Son","By human intellect"],2,
 "Colossians 2:2-3 — the mystery of God is Christ, in whom all treasures of wisdom and knowledge are hidden."),
(75,"Which of the following is NOT an example of modern day persuasive words?",
 ["Love is love","Know your faith","Be tolerant","Live your truth"],1,
 "\u201cKnow your faith\u201d is a call to grounded truth, not a vague modern slogan like the others."),
(76,"St. Paul writes \u201cwalk in Him\u201d. He did not write \u201cwalk with Him\u201d. What does the word \u201cin\u201d signify here?",
 ["That we can be almost similar to Christ, while still holding onto our lives","That He is already in us, so we don't have to be in Him",
  "\u201cIn\u201d and \u201cwith\u201d function the same here","That we must be united in Christ through our steadfastness"],3,
 "\u201cIn\u201d signifies real union — being rooted and built up in Him, not mere companionship."),
(77,"In the Thanksgiving Prayer, we say \u201cwe thank You for everything, concerning everything, and in everything,\u201d meaning \u201cwe thank you for all the good, all the bad, and everything in between.\u201d How does St. Paul describe this attitude?",
 ["Extreme","Unconditional","Abounding","Fullness"],2,
 "Colossians 2:7 — \u201cabounding... with thanksgiving.\u201d"),
(78,"When we sin, we can bring hardship upon ourselves, and we only are to blame. However when God allows us to experience trials…",
 ["We can't grow because we are still to blame","We can't grow because we can't be stronger than God",
  "We can grow by overcoming the trials via our strength","We can grow by deepening our faith in these hard times"],3,
 "God-permitted trials are opportunities to grow deeper in faith."),
(79,"Please reference 1 Corinthians 1:18-25 and Colossians 2:8-10 for the following question. To the world, a dead Man hung on a cross is not a powerful King. But St. Paul argues…",
 ["The traditions of men are foolish, not leading to life","Stumbling blocks of comprehension can't be overcome",
  "Academic knowledge is enough to live with Christ","The philosophers of this age have wisdom that is eternal"],0,
 "Worldly \u201cwisdom\u201d and human tradition are foolish next to the true wisdom of the Cross."),
(80,"What do Judaizers believe?",
 ["God can be understood through intense biblical study",
  "All the traditions of men by Jewish fathers, even if contradicting the Law of God must be strictly followed in order to live in communion with God",
  "Jesus is one of the many gods including Apollo and Hermes","Jesus is the Messiah who established His new covenant by His crucifixion and resurrection"],1,
 "Judaizers insisted on strict adherence to Jewish legal traditions, even beyond God's own Law."),
(81,"There are many Torah Laws regarding ritualistic cleansing as atonement for sins. While animal sacrifices are not maintained by Christians, the spirit of these laws remains today in the form of…",
 ["Wearing a clean white robe after baptism","Praying for forgiveness","The sacrament of repentance and confession","41 Kyrie eleyson's"],2,
 "Confession/repentance carries forward the spirit of ritual atonement in the New Covenant."),
(82,"When addressing Judaizer principles, St. Paul often reiterates to the Colossians that God cannot be known apart from Jesus Christ. Why?",
 ["The Judaizers taught unconditional tolerance of all beliefs","the Torah laws prior to the incarnation were not salvific",
  "The Judaizers added Christ to their pantheon of gods","The Colossians lived in utmost extravagance, equating earthly pleasure to divine blessing"],1,
 "The Old Testament law, on its own, could not save — salvation comes only through Christ."),
(83,"Why did God have Abraham and his descendants circumcise themselves as a sign of their covenant?",
 ["Co-suffering with Christ is how we live with Him","Circumcision, or priming, of the heart through baptism is how we make room for God in our daily lives",
  "God planned to abolish this law after the resurrection","Physical death of the body (or a body part) is the wage of sin"],1,
 "Circumcision foreshadowed the spiritual circumcision of the heart accomplished in baptism (Col 2:11-12)."),
(84,"We're told to put off the body of the sins of the flesh. What will take its place?",
 ["John 14:13","Philippians 3:20","Revelation 7:17","Ephesians 6:13"],3,
 "Putting off sin makes room for putting on the armor/new life described in Ephesians 6:13."),
(85,"In the song Oh Beloved is the phrase \u201cEvery time you sin a new, It's one more nail in My hand.\u201d How is this described in Colossians?",
 ["Atonement","Forgiveness","Handwriting","Justice"],2,
 "Colossians 2:14 calls the record of our debt \u201cthe handwriting of requirements... nailed to the cross.\u201d"),
(86,"In Colossians 2:13-14, we find 3 actions the Lord Christ performed that express how He paid the debt written in the \u201chandwriting\u201d and nullified its effect—what are they?",
 ["Forgave trespasses, wiped out handwriting, taken/nailed to the cross","Circumcised the flesh, wiped out handwriting, taken/nailed to the cross",
  "Wiped out handwriting, taken/nailed to the cross, restored us to the right","Forgave trespasses, triumphed over powers, wiped out handwriting"],0,
 "Colossians 2:13-14: He forgave our trespasses, wiped out the handwriting, and nailed it to the cross."),
(87,"In verse 2:16, who are the people who are judging?",
 ["The Colossians","The Christians","The Gnostics","The Judaizers"],3,
 "Colossians 2:16 addresses the Judaizers, who judged others by food/festival laws."),
(88,"God, out of His abundant love and grace, allows us sinners to worship Him. How does St. Paul describe this privilege?",
 ["Honor","Reward","Right","Rite"],1,
 "It is described as a right/access we have through Christ, not something we earn."),
(89,"The Ten Commandments God gave Moses strictly forbade the worship of idols. Now after the Resurrection of Christ, God still wants us to worship Him and Him alone. Similarly, St. Paul warns the Colossians against those who…",
 ["Do not hold fast to the Head","Are nourished and knit together","Ask intercession of the saints","Grow with the increase from God"],0,
 "Colossians 2:19 warns against those who fail to hold fast to Christ, the Head."),
(90,"The conclusion of chapter 2 advises against strict rules about what is ok and not ok to eat. How is this relevant to the fasts of the Orthodox Church?",
 ["We fast because some foods are not right at certain times of the year","We should not fast because St. Paul said food rules have no value",
  "We fast, not because food is morally bad, but as a spiritual exercise of saying no to sin","We should fast because celebrating a feast will feel much better"],2,
 "Orthodox fasting is a spiritual discipline of self-denial, not a claim that certain foods are inherently bad."),
(91,"What does \u201cdo not touch\u201d refer to from the Torah Laws?",
 ["Touching dead bodies or unclean animals made a person unclean","Touching clean people like priests made a person clean",
  "Touching the temple walls made a person clean","Touching a bloody animal sacrifice made a person clean forever"],0,
 "Touching unclean things (dead bodies, unclean animals) rendered a person ritually unclean."),
(92,"In verse 2:23, St. Paul boldly claims that saying no to certain foods everyday of the year actually has an opposite effect:",
 ["It does NOT guarantee our salvation","It does NOT help impulsiveness","It does NOT help us know Christ","It does NOT make us joyful"],1,
 "Colossians 2:23 — such self-imposed rules have no real value against the indulgence of the flesh; they don't guarantee salvation."),
(93,"Chapter 3 starts \u201cIf then you were raised with Christ\u201d, as if to say…",
 ["If you were raised from the dead, then you don't have to address sin anymore","If you seek things above, you cannot have anything on earth",
  "If you really believe Christ opened the path for us, then act like it and receive it","If Christ raised from the dead, continue your life as it was before"],2,
 "\u201cIf then\u201d is a call to live out what we claim to believe."),
(94,"Which is stronger language: \u201cseek\u201d or \u201cset your mind\u201d?",
 ["Set your mind","Seek","They're equal","They're both weak language"],0,
 "\u201cSet your mind\u201d (Col 3:2) is more decisive/intense than \u201cseek.\u201d"),
(95,"All of these verses from the Gospel according to St. Matthew demonstrate \u201cyour life is hidden with Christ in God\u201d EXCEPT…",
 ["\u201cAnd when you pray, do not be like the hypocrites...\u201d (Matthew 6:5)",
  "\u201cBut all their works they do to be seen by men...\u201d (Matthew 23:5)",
  "\u201cBut you, when you pray, go into your room...\u201d (Matthew 6:6)",
  "\u201cIf your hand or foot causes you to sin, cut it off and cast it from you.\u201d (Matthew 18:8)"],3,
 "Matthew 23:5 describes public showiness — the opposite of a hidden, private life with Christ."),
(96,"One practical step for controlling anger is…",
 ["Avoid daily activities (school, studying) that make you angry","Pray for patience right before you enter rooms/situations/groups where you've become upset in the past",
  "Only think happy thoughts all the time","Tell everyone who makes you angry to stay away"],1,
 "Proactive prayer before a known trigger situation is a concrete, practical step."),
(97,"In verse 3:5, the word \u201cmembers\u201d refers to the parts of ourselves that act in certain ways. From where do we receive help to put to death our members?",
 ["By giving thanks","The Holy Spirit","By serving","Circumcision"],1,
 "Romans 8:13 — by the Spirit we put to death the deeds of the flesh."),
(98,"When Jesus instructed us to turn the other cheek, He wanted us to reflect a mirror onto the person who wronged us. How do we do this practically?",
 ["When someone bothers you, respond with gentleness","When someone cheats you, cheat them back",
  "When someone steals from you, tell everybody","When someone falsely accuses you, do not help them in the future"],0,
 "Responding with gentleness reflects Christ's love back to the one who wronged us."),
(99,"What is the significance of the phrase \u201cBut now\u201d?",
 ["There's nothing we can do about that past","I'll plan to be better next month","We have a chance to repent and be better right now","Right now we have anger, wrath, etc…"],2,
 "Colossians 3:8 — \u201cbut now\u201d marks a decisive turning point to repent and change."),
(100,"What is the Devil's signature move?",
 ["Make us too guilty to sin, then afterwards too proud to reflect","Lie so that we sin, then afterwards make us feel too guilty to repent",
  "Lie so that we sin, then afterwards make us reflect and repent","Make us too guilty to sin, then afterwards shows us a different temptation"],1,
 "The devil tempts us to sin, then tries to trap us in shame so we never repent."),
(101,"We're instructed to \u201cput on the new self.\u201d This is step two. What is step one?",
 ["Romans 7:19","Colossians 2:11","Philippians 4:8","Galatians 4:31"],1,
 "Colossians 2:11's \u201cputting off\u201d the body of sin is step one, before putting on the new self."),
(102,"St. John Chrysostom says \u201cIf you have only this man [our nature inherited from Adam], you will obtain the same things with the others that have him.\u201d But what is the hope St. Paul provides?",
 ["The wrath of God is coming upon the sons of disobedience","There is neither slave nor free","Put to death idolatry","Christ is all, and is in all"],3,
 "Colossians 3:11 — \u201cChrist is all, and in all\u201d is the hope beyond mere fallen human nature."),
(103,"Verse 3:11 shows…",
 ["Greeks and Jews can't be saved","Christ is only in the slaves, not the free men","In Christ, our old nature is past, and we are a new creation","Circumcision satisfies the new covenant law"],2,
 "Colossians 3:11 shows old distinctions dissolve — in Christ we are a new creation."),
(104,"Humility is a gift from God which requires the grace of God as well as our struggle to grow in the virtue. How does St. Paul phrase this?",
 ["Take off","Try more","Turn aside","Put on"],3,
 "Colossians 3:12 — \u201cput on\u201d tender mercies, kindness, humility, meekness, patience."),
(105,"Some people confuse meekness and weakness. What is meekness?",
 ["Giving everything to another person","Bearing attack without returning it","Trusting God will protect you","Being quiet about the faith"],1,
 "Meekness is strength under control — bearing wrongs without retaliating."),
(106,"What must we do before we can forgive someone?",
 ["Repent and confess","Explain to them what they did wrong","Endure their wrongdoing patiently","Kindly ask them to stop"],2,
 "Recognizing our own need for forgiveness (through repentance/confession) shapes our ability to forgive others."),
(107,"St. Paul uses one word as the chief instruction to summarize all of these teachings. What is it?",
 ["Love","Bear","Endure","Hope"],0,
 "Colossians 3:14 — \u201cabove all these things put on love, which is the bond of perfection.\u201d"),
(108,"What is the secret to peace?",
 ["Thanksgiving","Kindness","Meekness","Mercy"],0,
 "Colossians 3:15 links the peace of God ruling our hearts with being thankful."),
(109,"How can we love our enemies?",
 ["We must find common interest","We must not acknowledge their wrongs","We must give them peace","We must love God first"],3,
 "Our capacity to love difficult people flows from loving God first."),
(110,"What's an easy way to let the word of Christ dwell in us?",
 ["Finishing one book each day","Psalms, hymns, spiritual songs","One thousand Jesus Prayers each day","Don't watch TV"],1,
 "Colossians 3:16 — teaching one another in psalms, hymns, and spiritual songs."),
(111,"Saint Isaac the Syrian said: \u201cThere is no gift without increase, except the one for which no thanks is given.\u201d How can we increase when our gift is trials?",
 ["We can only grow when we're given good things","We gain virtues like patience, thanksgiving, and depending on God",
  "We personally increase our suffering in order to participate alongside Christ's suffering","We look for a way out of trials so we can return to harmony with God"],1,
 "Trials, received with thanksgiving, grow virtues like patience and dependence on God."),
(112,"What is the point of verses 3:18-19 if I'm not married?",
 ["Obedience and love are virtues that everyone can grow in","I can notice when my father is not loving my mother",
  "I should obey those in my life, even when they lead me away from God","Nothing, I can skip this part"],0,
 "The underlying virtues (love, obedience) apply to everyone, married or not."),
(113,"We don't see slavery in our everyday lives. What is the point of verse 22 for us?",
 ["We can demand obedience of those below us","We can gain virtue if we obey insincerely",
  "Obedience to those in positions above us teaches us humility and patience","Performative prayer gets God's attention"],2,
 "The principle of respectful obedience to authority still teaches us humility and patience today."),
(114,"Let's say my brother is far from Christ. If he sees me living in the fear of God, even when it's hard, we pray that…",
 ["He be won over to Christ","He will make my life harder","He won't change","He will blaspheme against God"],0,
 "Faithful witness in hard circumstances can win others to Christ."),
(115,"When you study, your books are an altar, and you are the priest. Why?",
 ["Verse 19","Verse 22","Verse 23-24","Verse 25"],2,
 "Colossians 3:23-24 — \u201cwhatever you do, do it heartily, as to the Lord... you serve the Lord Christ.\u201d"),
(116,"Match the words to complete the verse:",
 ["Wives… submit to your own husbands… for this is well pleasing to the Lord",
  "Fathers… do not provoke your children… lest they become discouraged",
  "Children… love your parents… in sincerity of heart, fearing God",
  "Bondservants… submit to your own masters… and do not be bitter toward them"],1,
 "Colossians 3:21 accurately reads: \u201cFathers, do not provoke your children, lest they become discouraged.\u201d"),
(117,"Colossians 4:1 echoes what verse from the Lord's Prayer?",
 ["Thy Kingdom come, Thy Will be done","On earth as it is in Heaven","Give us this day our daily bread","Forgive us our trespasses, and we forgive those who trespass against us"],1,
 "Col 4:1 reminds masters they too have a Master in heaven — justice on earth should reflect heaven, \u201con earth as it is in heaven.\u201d"),
(118,"When is the best time to pray?",
 ["During a hardship","After a hardship is over","When you're about to enter a new hardship","All of the above"],3,
 "Colossians 4:2 calls us to continue earnestly in prayer at all times."),
(119,"Like a lifeguard at the beach is always watching for danger, so too are we called to be spiritually ___________",
 ["Calm","Peaceful","Vigilant","Thankful"],2,
 "Colossians 4:2 — \u201cbeing vigilant in it with thanksgiving.\u201d"),
(120,"Why did St. Paul want God to open a door?",
 ["He was in prison and wanted to leave","He wanted God to open the hearts of others, so they would receive Christ",
  "He was referencing John 10:9, where Christ says \u201cI am the door\u201d","He wanted to perform miracles so others would believe in Christ"],1,
 "Colossians 4:3 — praying for an open door to speak the mystery of Christ, that hearts would receive it."),
(121,"What should we do if a friend at school is resistant to hearing about Christ?",
 ["Force them to listen","Stop talking to them","Give them this book","Pray that God would open their heart to receive His Word"],3,
 "As Paul prayed for open doors and hearts, we should pray for our friends similarly."),
(122,"Asking others to pray for us is called ___________",
 ["Worship","Intercession","Thanksgiving","Service"],1,
 "This is called intercession."),
(123,"Many people don't follow Christ because they've been hurt by someone who is Christian. What is our responsibility to address this?",
 ["To demonstrate Christ in all our actions, so that others might be introduced to Him through us","Teach people all the commandments of God",
  "Try to figure out what went wrong with this person and rectify it ourselves","Those who have left the faith probably won't come back"],0,
 "Our lived example of Christ can introduce others to Him and repair harm done by poor witness."),
(124,"When we \u201cwalk in wisdom,\u201d we are to discern the SOURCE of spiritual debates. If discussions arise because people have different understandings, then that can be beneficial for both parties. But…",
 ["If debates arise because people are hostile to each other, there is no spiritual edification",
  "If debates arise because people are hostile to each other, that can be beneficial for both parties",
  "If you speak with grace, the other person won't understand the point you're trying to make",
  "If discussions devolve from theology to fighting matches, then everyone learns"],0,
 "Debates rooted in hostility rather than honest inquiry bear no spiritual fruit."),
(125,"As we go about our daily lives, we see and talk to people all the time. These moments are precious gifts from God. What should we do with them?",
 ["Let your speech be seasoned with malice","Walk carefree","Redeem the time","Run from responsibility"],2,
 "Colossians 4:5 — \u201credeeming the time.\u201d"),
(126,"If God has placed us in a position of responsibility, how should we exercise this when someone under us has done wrong?",
 ["Correct them firmly","Forgive them with love","Correct them with love","None of the above"],2,
 "Those in positions of responsibility should correct wrongdoing, but with love."),
(127,"If God has NOT placed us in a position of responsibility, how should we exercise this when someone has done wrong?",
 ["Correct them firmly","Forgive them with love","Correct them with love","None of the above"],1,
 "Without formal responsibility over someone, our role is to forgive with love, not correct."),
(128,"Speaking to Philemon (slave master), St. Paul reshapes the contemporary household through love by defending his runaway slave Onesimus: \u201creceive him forever, no longer as a slave but more than a slave—a beloved brother.\u201d What can we learn from this?",
 ["We can forgive people a few times, but after something really bad, they're out of chances",
  "We have to make sure our stuff is always in proper order so that we may serve God correctly",
  "We should free everybody of all their responsibilities",
  "We can be peacemakers between ourselves and God, between ourselves and others, and even within our own hearts when we forgive those who have wronged us"],3,
 "Paul's plea for Onesimus models becoming peacemakers through forgiveness at every level."),
(129,"St. Paul lists his friends in the ministry. Why?",
 ["Our spiritual journeys have both personal and communal components (both are necessary)","It is crucial we know exactly who was there with him",
  "The Colossians were looking for credentials, to verify where the information was coming from","Listing more people helps to raise awareness"],0,
 "Naming his co-laborers shows that Christian life is both personal and communal."),
(130,"Why does St. Paul write \u201cremember my chains\u201d?",
 ["He wanted pity from the Colossians for his suffering in prison","Co-suffering for the sake of Christ is how we grow in our relationship with Him",
  "He is calling himself the bondservant, as a reminder to obey the prison master","He wanted them to bail him out of prison"],1,
 "Remembering his chains points to co-suffering with Christ as a path of spiritual growth."),
(131,"John 3:14 and 12:32 both show…",
 ["The Cross had to be bronze to match Moses' serpent in the desert","Christ was lifted up, but we are not drawn to Him by this action",
  "The Cross was not a last minute scheme to save humanity, but God's intent from the beginning","God always had a plan to save humanity, but the Cross itself was not specific to that plan"],2,
 "The bronze serpent typology (John 3:14) shows the Cross was planned by God from the beginning, not an accident."),
(132,"Crucifixion was a __________ practice",
 ["Jewish","Roman","Greek","Egyptian"],1,
 "Crucifixion was a Roman method of execution."),
(133,"Matthew 27 tells us Judas returned the silver, and the priests refused to put \u201cblood money\u201d in the treasury. What does this show?",
 ["The high priests did not want the public responsibility of killing Jesus","The priests told Judas to give the money to Pilate so Rome would take the blame",
  "The priests told Judas to give the money to the poor because there were many poor Jews at the time","The priests had so much money because of their position that they didn't need any from Judas"],0,
 "Refusing the \u201cblood money\u201d shows the priests' hypocrisy in avoiding open responsibility for Christ's death."),
(134,"What is the significance of both the Jews and Romans being involved in the death of Christ?",
 ["Only Jews and Romans can now be saved","Technically it was Rome who completed the execution, so Romans cannot be saved in the end",
  "It was a minor planning detail unrelated to the story of salvation","Christ died because of the Jews and Gentiles, meaning His salvation is open to the whole world"],3,
 "Both Jew and Gentile were involved, showing salvation through the Cross is offered to the whole world."),
(135,"\u201cFor the wages of sin is death\u201d comes from",
 ["Prayer of Reconciliation","Romans 6:23","Colossians 3:4","Basilian Liturgy"],1,
 "Romans 6:23."),
(136,"\u201cYou did not leave us until the end\u201d comes from",
 ["Prayer of Reconciliation","Romans 6:23","Colossians 3:4","Basilian Liturgy"],3,
 "This line is from the Prayer of Reconciliation in the Coptic Liturgy."),
(137,"In the conclusion of each Agpeya hour, we say \u201cwho [God] does not wish the death of the sinner but rather that he returns and lives.\u201d Which verse is this echoing?",
 ["Ezekiel 33:11","Exodus 23:7","Acts 17:28","1 Peter 1:15-16"],0,
 "Ezekiel 33:11 — God has no pleasure in the death of the wicked, but that they turn and live."),
(138,"What does the word \u201cHoly\u201d mean?",
 ["To be a prophet, telling the people about Christ","To be merciful, accepting people as they are","To be set apart, not mingled with anything wrong","To be as perfect as a human can be"],2,
 "Holy means set apart, undefiled by anything wrong."),
(139,"From the previous question, let us understand how blessed we are: Even though God is just, holy, and hates evil, He also…",
 ["Desires the evil to die","Loves sinners","Only helps the righteous","Hates sinners"],1,
 "God hates evil but loves sinners — this tension is resolved at the Cross."),
(140,"Psalm 85:10 solves",
 ["The Schisms in the Church","The Jew vs Gentile Discussions","The Council Debates","The Divine Dilemma"],3,
 "Mercy and truth meeting resolves the Divine Dilemma between God's love and justice."),
(141,"Our savior must be…",
 ["Unlimited","Human","Unlimited and human","Unlimited or human, but not both"],2,
 "The Savior must be both unlimited (infinite) and human — fully God and fully man."),
(142,"\u201cHe took what is ours and gave us what is His\u201d from the Friday Theotokias of the Midnight Praises reflects which verse?",
 ["2 Corinthians 5:21","Hebrews 4:15","Hosea 13:14","Acts 2:24"],0,
 "2 Corinthians 5:21 — He who knew no sin became sin for us, that we might become God's righteousness."),
(143,"\u201cTrampled death by death\u201d indicates that, in order to save us, Christ must…",
 ["Die, unwillingly","Die, forcefully","Be stronger than death to defeat it","Be weaker than death in order to fill the death"],2,
 "To trample death, Christ had to be stronger than death itself."),
(144,"Isaiah 43:1 shows that the Savior must also be",
 ["Stronger than death","The Creator","The Substitute","Holy"],1,
 "Isaiah 43:1 — \u201cThus says the LORD who created you... I have redeemed you\u201d links Creator and Redeemer."),
(145,"All of the following are attributes of a fitting Savior, EXCEPT…",
 ["Infinite","Holy","Limited","Creator"],2,
 "The Savior must be unlimited (infinite), not limited."),
(146,"Someone had to die for the sins we commit. But God loves us and does not desire our death. The incarnation was the perfect solution to our dilemma. Why?",
 ["God can die","A sinful human can save other sinful humans","The Incarnate Son of God has both flesh to substitute for flesh and immortality to cover eternity","It was a miracle"],2,
 "The God-Man uniquely has flesh to substitute for our flesh and divine immortality sufficient for eternity."),
(147,"Here, in the person of the Lord Jesus Christ, all the qualifications of the Savior are complete. He alone is _______, able to do all things; ____ and without evil; stronger than ________; and the ________ who became a human to die on behalf of all people.",
 ["Infinite; Holy; death; Creator","Limited; Holy; Satan; Creator","Infinite; good; Satan; sinner","Powerful; perfect; God; man"],0,
 "Christ is Infinite, Holy, stronger than death, and the Creator who became man."),
(148,"As an alternative, the savior could have been…",
 ["An angel","A prophet","Virgin Mary","No one else"],3,
 "Only the God-Man uniquely meets every qualification of Savior — no one else could fulfill this role."),
(149,"When David beat Goliath, the Israelites \u201cwon\u201d even though they didn't fight Goliath. Also as a sign of Christ's victory…",
 ["We have to fight the giants of our time","We don't have to die on a Cross, but stay close to Him through belief and spiritual practices",
  "We sling a single stone like David, which is the Word of God","We can carry our cross without belief"],1,
 "Christ already won the victory; we share in it by staying close to Him through faith and practice, not by re-fighting the battle."),
(150,"Why was it crucial that the sick people LOOKED at the Bronze Serpent to receive healing?",
 ["Looking is how the healing was transferred to the people","People who didn't look were also healed",
  "Looking represents belief and synergistic cooperation with God","That's what God commanded, but it's not crucial to understand"],2,
 "The act of looking represents faith and willing cooperation with God's provided healing."),
(151,"In regards to the previous question, what is the result of looking?",
 ["By looking at the snake, the snake loses its power; by looking at death, death loses its power.","Death is less scary, but still real",
  "Moses became the savior of those in the wilderness","Looking has no consequence because it is merely a symbol"],0,
 "Looking at the bronze serpent (a type of the Cross) strips the destructive power of the thing itself, just as looking to the Cross strips death of its power."),
(152,"Why was God adamant that no bones be broken in the sacrificial lamb?",
 ["It had to be done so the ritual would be performed correctly","Blood represents sin, which Christ had none of",
  "Blood from breaking bones represents life, so Christ gave His blood for us","Because we (the Church) are His Body, and these imperfections (broken bones) represent division, which He didn't want"],3,
 "Unbroken bones symbolize the unbroken unity of Christ's Body, the Church."),
(153,"Similarly, why wasn't Christ beheaded?",
 ["If Christ is the head, and we are His Body, beheading would represent a separation between God and man, which is not His desire","Christ was a Roman citizen, so beheading was not appropriate",
  "Christ was Jewish, so beheading was appropriate","Beheading does not involve breaking any bones"],0,
 "As Head of the Body, Christ being beheaded would symbolize separation between God and humanity — not His desire."),
(154,"Christ chose the Cross for many reasons. Which reason represents life via death?",
 ["\u201cI am the Way, the Truth, and the Life\u201d (John 14:6)","The Roman execution system never included stoning",
  "While Christ was dead, He remained standing (on the Cross)","The Jewish priests were not allowed to put anyone to death"],2,
 "Even in death, Christ remained upright on the Cross — a picture of life persisting through death."),
(155,"Christ came for all, including those who believe without proof and those who wish for further explanation. He came for all. Who is the best example of the latter?",
 ["St. Mary","St. Athanasius","St. Peter","St. Thomas"],3,
 "St. Thomas needed further proof before believing (John 20)."),
(156,"The Cross healed",
 ["Our bodies","Our souls","Our bodies and souls","Our victory"],2,
 "The Cross brings healing to both body and soul."),
(157,"Where does the following verse come from? \u201cThen He said to them all, \u2018If anyone desires to come after Me, let him deny himself, and take up his cross daily, and follow Me.\u2019\u201d",
 ["Luke 24:26","John 3:16","Psalm 84:10","Luke 9:23"],3,
 "Luke 9:23."),
(158,"On Galatians 5:17, St. John Chrysostom says the things that truly oppose each other are virtue and wickedness, not soul and body. What is his point?",
 ["Our flesh and spirit are forever at war with each other","We can work together with the Holy Spirit, who elevates us",
  "The flesh represents virtue, and the spirit represents wickedness","Brownness and whiteness can never coexist in a person"],1,
 "Body and soul are meant to cooperate together, elevated by the Holy Spirit, not locked in permanent war."),
(159,"If your parents gift you a new phone, how should you behave to preserve it as long as possible?",
 ["Give it back to them","Throw it around carelessly","Break it in order to get a new one","Charge it, clean it, protect it with a case"],3,
 "Careful, ongoing maintenance preserves a gift."),
(160,"If your Father in Heaven gifts you a new nature, how should you behave to preserve it as long as possible?",
 ["Give it back to Him","Handle it carelessly","Destroy it in order to get a new one","Feed it with His Word, clean it with repentance/confession, protect it with praise and sacraments"],3,
 "Our new nature is nourished by God's Word, cleansed by repentance/confession, protected by praise and the sacraments."),
(161,"What is asceticism?",
 ["Living in the desert with very little food/water","Exercise of discipline on the path to holiness","Torturing yourself to gain virtues","Only reserved for the monks"],1,
 "Asceticism is disciplined spiritual exercise on the path toward holiness — for everyone, not only monastics."),
(162,"St. Isaac said \u201cthe peace that comes from worldly actions is a delusion.\u201d What verse is he referencing?",
 ["Philippians 4:6-7","James 3:18","John 14:27","Colossians 3:15"],2,
 "John 14:27 — Christ's peace is unlike the peace the world gives."),
(163,"If everyone in the room is speaking poorly about someone who is not present, why should we speak up to defend that person? Select all that apply.",
 ["When we speak up, we may be mocked, and that mockery is how we live with Christ (see Matthew 5:11-12)",
  "Peace is not something that appears spontaneously, we have to make an effort (see Romans 12:18)",
  "When the others hear a viewpoint they hadn't considered before, they might become more forgiving (see 2 Corinthians 5:18-20)",
  "When the others hear a viewpoint they hadn't considered before, they might see that they were wrong to gossip (see Romans 12:20-21)"],[1,2,3],
 "Speaking up takes effort toward peace (Rom 12:18), can move others toward forgiveness (2 Cor 5:18-20), and can correct gossip (Rom 12:20-21)."),
(164,"Acts 5:41 reads \u201cSo they departed from the presence of the council, rejoicing that they were counted worthy to suffer shame for His name.\u201d Which type of peace are the apostles demonstrating here?",
 ["Peace of Mind","Peace of Heart","Peace in Relationships","Peace of Conscience"],1,
 "Their rejoicing under persecution reflects a clear peace of conscience before God."),
(165,"Happiness is a momentary feeling of bliss. Conversely, peace…",
 ["Grows when you choose not to share it","Is a human creation","Cannot be taken away by hardship","Lasts only one moment"],2,
 "Unlike fleeting happiness, true peace endures through hardship."),
(166,"Christ tells us \u201cPeace I leave with you, My peace I give to you; not as the world gives do I give to you\u201d(John 14:27). Identify the peace from God (not the world)",
 ["Comfort and luxury","Money and good food","Coolness and repose","Vacation and free time"],2,
 "God's peace is described as \u201ccoolness and repose\u201d — inward rest, unlike worldly comfort."),
(167,"Identify the path to reassurance",
 ["Acknowledge there is a God, believe in His ability, trust He is for us","Choose a god, praise his ability, ask for reassurance",
  "Create a god, believe in his ability, trust he will help","Acknowledge there is God, acknowledge His ability, question if He is for us"],0,
 "Reassurance builds on acknowledging God exists, believing His power, and trusting He is for us."),
(168,"Therefore the path to peace must include…",
 ["Our quietness","The Christotokos","The gods","The Prince of Peace"],3,
 "True peace is found in Christ, the Prince of Peace (Isaiah 9:6)."),
(169,"What can we learn from the European Ermine? (See Matthew 16:26)",
 ["The devil will not try to trap us using our principles","Protecting our lives is the most important thing",
  "To choose purity over our very lives","We shouldn't clean ourselves in order to remain safe"],2,
 "Legend says the ermine would rather be caught than dirty its white coat — choosing purity even over its life."),
(170,"Purity is defined as…",
 ["Deprivation or suppression of the eyes, ears, mouth, hands, thoughts","Refraining from physical sins like action, watching, hearing, or imagination",
  "Saying no to everything out of uninformed principle","Guarding the sense of the heart to be united with our pure God"],3,
 "Purity is about guarding the heart to remain united with our pure God, not mere external suppression."),
(171,"Before the Last Supper, Christ told St. Peter about washing. Christ informed the disciples that they will become impure, but…",
 ["He spoke of repentance/confession as the path back to union with Him","Once you've fallen, you cannot become pure again",
  "Every sin throughout our lives requires re-baptism","The washing metaphors were simply literal"],0,
 "Ongoing repentance/confession (\u201cwashing the feet\u201d) restores union with Christ after falling."),
(172,"The earth is already the domain of the devil (\u201cThe prince of this world\u201d, John 14:30). The least we can do is…",
 ["Let him inside us because he already influences the world","Guard our minds so they don't become his playground too",
  "Exorcise him out of every single mind","Surrender to sin because rising again is futile"],1,
 "We should guard our own minds so they aren't overtaken as well."),
(173,"\u201cThe pure person is not just one who has reached perfection in purity, but also one who longs to reach it.\u201d What does this imply?",
 ["Once you're content with your status, you don't need to try anymore","Perfection is attainable","Purity is a lifelong pursuit, and we can all progress further","Humility is not a component of purity"],2,
 "Purity is a continual, lifelong pursuit of growth."),
(174,"Which verse represents the element of escaping?",
 ["Jeremiah 4:14","Psalm 63:5","Psalm 57:2","2 Timothy 2:22"],3,
 "2 Timothy 2:22 — \u201cFlee also youthful lusts.\u201d"),
(175,"There are different types of prostrations. When reviewing our sins, what is the mechanism of a metanoia?",
 ["Bowing to the sin saying \u201cI can defeat you without Christ\u201d","It's a prayer rule that cannot be understood fundamentally",
  "We aim to bury the sin as we go down, and rise with Christ as we stand back up","The physical act has no spiritual influence"],2,
 "The prostration (metanoia) symbolizes burying sin and rising anew with Christ."),
(176,"What is a good servant, but a bad master?",
 ["Obedience","Love","Money","God"],2,
 "Money serves us well but makes a terrible master if it rules our hearts."),
(177,"What should be our position on contentment and wealth?",
 ["The more I have, the more I can donate","Don't let your happiness depend on something you may lose",
  "All wealth is bad and I shouldn't try to make money","Money is both the way to the goal and the goal itself"],1,
 "True contentment doesn't hinge on things that can be lost."),
(178,"The last time you fasted, did you perish? No! St. Paul says in Philippians 4:11-13 that contentment can be reached…",
 ["Only when things are going well","Only when things are going poorly","Only when surrounded by others going through a similar experience","In any circumstance, through Christ"],3,
 "Philippians 4:11-13 — content in any and every circumstance, through Christ who strengthens."),
(179,"Why are St. Paul's many travels and sufferings described as a \u201cschool\u201d?",
 ["He studied the Torah and upheld it intensely before Christ appeared to him","He started many schools for his disciples to learn about the Gospel",
  "These circumstances taught him to be content through anything","After Christ appeared to him, he immediately understood how to be content all the time"],2,
 "His many trials taught (schooled) him to be content in every circumstance."),
(180,"What is the easiest way to start practicing active contentment right now?",
 ["Say \u201cthank God\u201d as often as you can","List every bad thing God has ever given you","Meditate on all the good things to come","List every single struggle God has allowed for your benefit"],0,
 "Simple, frequent thanksgiving is an easy practical start."),
(181,"Which verse(s) teach us to be content throughout trials?",
 ["1 John 2:3-4","James 1:2-4","Proverbs 29:20","Romans 12:9"],1,
 "James 1:2-4 — count it all joy when you fall into various trials, which produce patience."),
(182,"Eve fell (as do we) because she did not fully grasp the commandment against the tree. Why?",
 ["She didn't memorize it","She followed it precisely, without adding to it","She saw it as a superficial rule, not internalizing its significance","The serpent could not easily trap her"],2,
 "Eve treated the command as a superficial rule rather than internalizing its deeper significance."),
(183,"Knowledge is…",
 ["Acquired more and more until, and no harm can result","Acceptable from any source, as learning is always a good thing",
  "The means to an intellectual vacuum","A gift from God that can be cultivated through our beneficent pursuit"],3,
 "Knowledge is a gift from God, meant to be cultivated for good purposes."),
(184,"Does this devil give us knowledge?",
 ["No, he is only bad","No, because God is the source of knowledge","Yes, either lies or malicious truths","Yes, he gives freely like God does"],2,
 "The devil can offer \u201cknowledge\u201d that is either outright lies or truths twisted toward harm."),
(185,"The unrelenting pursuit of non-spiritual academic knowledge (i.e. bringing home space rocks) ultimately feeds…",
 ["Our longing for understanding of God","Our pride because we discovered it","Our desire for peace","Our hope of the age to come"],1,
 "Purely academic achievement, disconnected from God, tends to feed pride rather than spiritual growth."),
(186,"If you know your mother's favorite flower, but don't gift it to her, then this knowledge is useless. Similarly…",
 ["God's will for our lives is not a literary pursuit but a lived experience","We should read the Bible as a theoretical path to utopia",
  "Jesus' life was an example for only the holiest people to follow","It's ok to offer to God something other than what He wants"],0,
 "Knowing God's will means nothing unless we live it out."),
(187,"How can we know how God wants us to live? Select all that apply.",
 ["Read the Bible","Internalize our Sunday School lessons","Observe the Christ-like behavior of others","Prayer and repentance"],[0,1,2,3],
 "Scripture, sound teaching, godly example, and prayer/repentance all reveal how God wants us to live."),
(188,"One component of our spiritual journeys is knowing how to invest our energy. See 1 Corinthians 3:6-8 and Matthew 6:33, then choose the correct statement:",
 ["When we prioritize our earthly responsibilities over God, He does not love us","When we invest our time in heavenly matters, God multiplies all our time",
  "Our goal is to leave our prayers until right before bedtime when we are most tired","Heavenly and earthly matters cannot coexist"],1,
 "\u201cSeek first the kingdom\u201d — God multiplies the fruit of time invested in Him."),
(189,"We live in a confused world, so in order to walk righteously within our time/era, we must…",
 ["Be a light to the world by agreeing with everyone","Say \u201cno\u201d to all evil with a vicious tone","Interact wisely, remaining solid on principles","Re-align with changing perspectives"],2,
 "We're called to interact wisely with the world while holding firm to our principles."),
(190,"If I pour ________ into a cup, then _________ will come out when I empty it.",
 ["Water; poison","Poison; water","Poison; poison","Water; nothing"],2,
 "Whatever goes in comes back out — poison in, poison out."),
(191,"What's the point of the previous question?",
 ["Our minds are not weak, i.e. we can't be influenced by the world","Whatever we allow to penetrate our minds will eventually become our way of thinking (whether good or bad)",
  "It is the responsibility of our parents/priests/servants to protect all of our thoughts","To demonstrate a miracle"],1,
 "What we let into our minds shapes how we think, for good or bad."),
(192,"Even if you repent, confess, and are absolved of the sin of gossip, the earthly consequences still persist because…",
 ["The transmission of harmful knowledge was passed to others","Peace can never be fully attained","You're sin was not forgiven","There's no more consequences after receiving absolution"],0,
 "Even after forgiveness, the harmful information already shared with others can't be un-transmitted."),
(193,"What's a good verse to consider when contemplating the benefit of suspicious knowledge?",
 ["\u201cAnd I will give you shepherds according to My heart...\u201d (Jeremiah 3:15)","\u201cI thank my God always concerning you...\u201d (1 Corinthians 1:4-5)",
  "\u201cGrace and peace be yours in abundance through the knowledge of God...\u201d (2 Peter 1:2)","\u201cAll things are lawful for me, but not all things are helpful; ... not all things edify\u201d (1 Corinthians 10:23)"],3,
 "1 Corinthians 10:23 reminds us to weigh whether knowledge is helpful and edifying, not just \u201clawful.\u201d"),
(194,"Why is your father of confession a safe person to discuss with?",
 ["He's had personal experience will all your troubles/questions","His words put you on a path toward priesthood",
  "He places your salvation at the forefront of his guidance","His instructions are intended to make your life more difficult"],2,
 "A father of confession guides you with your salvation as the priority."),
]

assert len(Q) == 194, len(Q)

DAYS = [
 (1,"Week 1","Monday","None separate","Q1-6","Why the Cross? Incarnation and Redemption","25 min",1,6),
 (2,"Week 1","Tuesday","None separate","Q7-12","The Sign of the Cross and Why Christ Chose the Cross","25 min",7,12),
 (3,"Week 1","Wednesday","None separate","Q13-15","The Cross in Liturgy and in Trials","20 min",13,15),
 (4,"Week 1","Thursday","Colossians 1:1-8","Q16-25","Colossians: Faith, Hope, Love, and Fruit","25-30 min",16,25),
 (5,"Week 1","Friday","Colossians 1:9-14","Q26-40","Knowledge That Becomes Action","30 min",26,40),
 (6,"Week 2","Monday","Colossians 1:15-17","Q41-55","Who Is Christ? Image, Creator, and Firstborn","30 min",41,55),
 (7,"Week 2","Tuesday","Colossians 1:18-27","Q56-70","Christ the Head, Reconciliation, and Hope","30-35 min",56,70),
 (8,"Week 2","Wednesday","Colossians 2:1-3","Q71-74","The Mystery Is Christ","20-25 min",71,74),
 (9,"Week 2","Thursday","Colossians 2:4-13","Q75-84","Walk in Christ; Don't Be Captured by False Teaching","30 min",75,84),
 (10,"Week 2","Friday","Colossians 2:14-23","Q85-92","The Debt Is Cancelled; Hold Fast to Christ","30 min",85,92),
 (11,"Week 3","Monday","Colossians 3:1-8","Q93-100","Seek Things Above and Put Sin to Death","25 min",93,100),
 (12,"Week 3","Tuesday","Colossians 3:9-17","Q101-111","Put Off the Old; Put On the New","30 min",101,111),
 (13,"Week 3","Wednesday","Colossians 3:18-25","Q112-116","Faithfulness in Relationships and Responsibilities","20 min",112,116),
 (14,"Week 3","Thursday","Colossians 4:1-18","Q117-130","Prayer, Witness, Wise Speech, and Christian Community","30 min",117,130),
 (15,"Week 3","Friday","None separate","Q131-147","Why Death? Why the Incarnate Savior?","30-35 min",131,147),
 (16,"Week 4","Monday","None separate","Q148-157","Why the Cross Specifically? Victory and Healing","30-35 min",148,157),
 (17,"Week 4","Tuesday","None separate","Q158-168","Blemished Yet Blameless: Peace and Spiritual Discipline","30 min",158,168),
 (18,"Week 4","Wednesday","None separate","Q169-181","Purity, Repentance, Contentment, and Inner Freedom","30 min",169,181),
 (19,"Week 4","Thursday","None separate","Q182-191","True Knowledge: Knowing Truth So We Can Live It","30 min",182,191),
 (20,"Week 4","Friday","None separate","Q192-194 + Review","Wisdom, Safe Sources, Counsel, and Mature Thinking","25-30 min",192,194),
]

LESSONS = {
1:"The Cross is not a random tragedy — it holds together real suffering and real victory. God could not simply overlook sin, or His justice would mean nothing; but He also loved humanity too much to leave us in death. Psalm 85:10 pictures the answer: mercy and truth, righteousness and peace, meeting together. Because Christ is the Creator, He alone could renew our corrupted nature — redemption required re-creation, and only the Maker can remake.",
2:"Small physical actions carry deep meaning. Signing the Cross from left to right recalls the Holy Spirit moving us from darkness into light. Hebrews 12:2 and 1 Peter 2:24 both center on the same truth: Christ personally endured suffering for us. Galatians 3:13 shows He became a curse for us, taking the death sentence that was ours. Spiritual death (separation from God) and mortal death (subjection to a corrupt realm) are both conquered through Him, and St. Athanasius reminds us Christ was lifted up to draw us to Himself.",
3:"This year (2026) marks 1700 years since St. Helena's discovery of the True Cross (traditionally dated 326 AD). Trials are not random either — God can use them, like Abraham's testing, to protect us from future sin. The apostles in Acts 5:41 rejoiced to suffer shame for Christ's name, showing that real joy can come from tribulation. And in our prayers, the Litany of the Departed reminds us that death is a step toward the realm of the saints, not an end.",
4:"Colossae sat in what is now Turkey. St. Paul never visited it himself — the church was founded by Epaphras, who consulted Paul when false teaching arose. Ephesians and Colossians work together: both describe Christ as the Head of the Church, His Body. Paul opens by blessing the Colossians and praising their faith and love, which Epaphras reported to him. Their genuine hearing of the Gospel, not mere theory, is what let the message bear fruit and grow among them.",
5:"Paul prays that the Colossians be filled with knowledge (gnosis) that leads to action (praxis) — echoing the Hebrew Shema's call to \u201chear... and love.\u201d Understanding morals theoretically is not enough; it must be lived. This matters because Gnostics claimed God is known only through hidden, secret knowledge rather than Scripture and the Church's teaching — a serious error the Holy Spirit corrects by teaching us daily (John 14:26) and interceding through our prayers (Romans 8:26). Salvation is synergistic: God's grace strengthens us, but as St. Augustine says, He who created us without us will not save us without us — we participate, choosing daily whether to walk with Him, even in something as small as refusing to cheat on a test.",
6:"Colossians 1:15-17 answers a false idea that we can reach the Father without Christ. Christ is called \u201cthe image of the invisible God\u201d and \u201cfirstborn\u201d — meaning eternally begotten, not created, and the one through whom we truly glimpse the Father (since no one has seen the Father directly). \u201cAll things were created through Him and for Him,\u201d so nothing that exists is our own doing to claim. Like a potter's vase serving the potter's purpose, we exist to serve God's purposes, not merely our own.",
7:"Christ is \u201cthe firstborn from the dead\u201d — unlike Lazarus, who was raised but died again, Christ rose to live forever. As Head of His Body, the Church, Christ holds preeminence over all creation; we worship Him alone, never angels or anything else (Revelation 22:8-9). Because we inherited a \u2018dead body\u2019 through Adam, we needed adoption into Christ's renewed Body (Romans 8:15) — merely being raised like Lazarus wouldn't fix our corrupted nature; God had to become man to truly renew it, as St. Athanasius says: \u201cGod became man so that man might become like god.\u201d It pleased the Father that in Christ all the fullness dwells (1:19), and through Him — and Him alone — estranged humanity is reconciled to God, sacramentally renewed through the Eucharist, and called to remain grounded, not moved away from the hope of the Gospel.",
8:"Chapter 2 opens with St. Paul longing for the Colossians to have real, practical understanding — not the hidden \u201cmystery\u201d claimed by Gnostics, but the true mystery of God, which is Christ Himself, \u201cin whom are hidden all the treasures of wisdom and knowledge.\u201d Love — the fruit of the Holy Spirit — is what lets us stay united to others even when they've wronged us. To \u201cwalk in Him\u201d (not merely \u201cwith\u201d Him) means real union with Christ, and this whole posture should overflow with abounding thanksgiving.",
9:"Trials God allows can deepen our faith rather than defeat us. To the world, a crucified man is not a king — but Paul insists worldly wisdom and human tradition are foolish next to the Cross. This section confronts the Judaizers, who demanded strict adherence to Jewish legal tradition even beyond God's actual Law, insisting the old covenant law (on its own, before Christ) could never save. Circumcision under the old covenant foreshadowed the spiritual circumcision of the heart now accomplished through baptism, and confession/repentance today carries forward the spirit of the old ritual atonement laws.",
10:"Colossians 2:13-14 lists three things Christ did to cancel our debt: He forgave our trespasses, wiped out the handwriting (record) against us, and nailed it to the Cross — just as the song lyric \u201cevery time you sin a new, it's one more nail in My hand\u201d expresses in modern language. Verse 16 warns against Judaizers who judged others by food and festival laws. We are given the right to worship God through Christ, and warned against failing to \u201chold fast to the Head.\u201d Orthodox fasting fits here too: we fast not because food is evil, but as a spiritual exercise of saying no to sin — self-imposed food rules alone, Paul says, don't guarantee our salvation.",
11:"Chapter 3 begins, \u201cIf then you were raised with Christ\u201d — a call to actually live out what we believe. \u201cSet your mind\u201d (stronger language than \u201cseek\u201d) on things above. Living \u201chidden with Christ in God\u201d means private, sincere devotion rather than public showiness (contrast Matthew 6:5-6 with Matthew 23:5). Practical anger control might mean praying for patience right before entering a known difficult situation. The Holy Spirit helps us put our sinful \u201cmembers\u201d to death (Romans 8:13), and \u201cbut now\u201d (3:8) marks our chance to repent right now — resisting the devil's usual trick of tempting us to sin, then burying us in guilt so we never repent.",
12:"\u201cPutting off\u201d the old self (Colossians 2:11) comes before \u201cputting on\u201d the new self — two steps. St. Paul offers real hope beyond our fallen nature inherited from Adam: \u201cChrist is all, and in all\u201d — in Him, old distinctions and our old nature are truly past. We're told to \u201cput on\u201d tender mercies, kindness, humility, meekness, and patience; meekness means bearing wrong without retaliating, not weakness. Above everything, love is \u201cthe bond of perfection\u201d that holds it all together, and the peace of God ruling our hearts is tied directly to being thankful. Letting \u201cthe word of Christ dwell in us richly\u201d can be as simple as psalms, hymns, and spiritual songs — and trials received with thanksgiving actually grow our virtues rather than just burden us.",
13:"Even without being married, the underlying virtues Paul commends — love, obedience, humility, patience — apply to everyone. Though slavery isn't part of our world, the principle of respectful obedience to those in authority over us still teaches humility and patience. Living faithfully, even when it's hard, can help win others (even distant loved ones) toward Christ. \u201cWhatever you do, do it heartily, as to the Lord\u201d (3:23-24) — treating even our studies as an offering, our books an altar and ourselves the priest.",
14:"Colossians 4 turns to prayer, witness, and community. We're called to \u201ccontinue earnestly in prayer,\u201d being \u201cvigilant... with thanksgiving\u201d at all times — before, during, and after hardship. Paul prayed for an open door to speak Christ's mystery, and for hearts to receive it; we can pray the same for resistant friends. Our lived example of Christ matters, especially for those hurt by poor Christian witness in the past. Debates rooted in hostility bear no spiritual fruit, but \u201credeeming the time\u201d in our everyday interactions is a gift. Those in authority should correct wrongdoing with love; those without that authority should simply forgive with love. Paul's appeal for the runaway slave Onesimus — \u201creceive him... as a beloved brother\u201d — models becoming peacemakers through forgiveness, and his own \u201cchains\u201d model co-suffering for Christ as a path of growth.",
15:"Why did Christ have to die, and why through incarnation? The Cross was planned by God from the beginning (foreshadowed by the bronze serpent, John 3:14), not a last-minute fix — crucifixion itself was simply the Roman method of execution God's providence used. Both Jew and Gentile were involved in His death, showing salvation is offered to the whole world. God is holy and hates evil, yet loves sinners (Psalm 85:10 resolves this \u2018Divine Dilemma\u2019). A fitting Savior must be unlimited (infinite), holy, stronger than death, and the Creator who became human — only the Incarnate Son of God has both flesh to substitute for our flesh and the immortality to cover eternity. No one else — not an angel, not a prophet — could qualify.",
16:"Old Testament \u2018types\u2019 point forward to the Cross. Like David's victory over Goliath won on Israel's behalf, Christ's victory is already won — we share in it by staying close to Him through belief and spiritual practice, not by refighting the battle ourselves. Looking at the bronze serpent to be healed required belief and cooperation with God, just as looking to the Cross does. Unbroken bones in the Passover lamb, and Christ not being beheaded, both point to the unity of Christ's Body, the Church — the Head must not be separated from His Body. Christ remained standing even in death, a picture of life through death, and He came for all — those who believe without proof, and those (like St. Thomas) who need more. The Cross heals both body and soul, and calls us daily to \u201cdeny himself, and take up his cross daily.\u201d",
17:"Body and soul are not natural enemies — the real war is between virtue and wickedness, and body and soul can work together under the Holy Spirit. Just as we protect a treasured gift (like a new phone), we should feed our new nature with God's Word, cleanse it through repentance and confession, and protect it with praise and the sacraments. Asceticism is disciplined spiritual exercise toward holiness for everyone, not only monastics. Worldly peace is a delusion (St. Isaac); we should even speak up for someone being gossiped about, because peace takes real effort and can move others toward repentance. True peace of conscience, like the apostles' rejoicing under persecution, doesn't depend on circumstance — it's the \u201ccoolness and repose\u201d Christ gives, not the world's comfort, found in the Prince of Peace.",
18:"Purity is about guarding the heart to stay united with our pure God — not just avoiding actions, like the legendary ermine who would rather be caught than dirty its white coat, choosing purity over even its own safety. We will all become impure at times, but Christ's washing of the disciples' feet shows ongoing repentance and confession restores our union with Him; purity is a lifelong pursuit, not a finished destination. We're called to flee temptation (2 Timothy 2:22) and to \u201cbury\u201d sin and rise with Christ in every prostration. Money is a good servant but bad master, and real contentment — as Paul learned through many trials (Philippians 4:11-13) — doesn't depend on wealth or circumstance, but is possible in Christ at all times.",
19:"Eve fell not from ignorance of the command, but because she treated it as a superficial rule rather than internalizing its true significance — a pattern we can repeat. Knowledge itself is a gift from God, but the devil can offer his own kind of \u201cknowledge\u201d — either outright lies or twisted truths — and purely academic pursuit disconnected from God tends to feed pride rather than draw us closer to Him. Just as knowing your mother's favorite flower is useless if you never give it to her, knowing God's will means nothing unless we live it out — through Scripture, godly example, and prayer.",
20:"Investing our energy in heavenly things lets God multiply the fruit of our time (Matthew 6:33); we're called to interact wisely with the world while staying solid on our principles. Whatever we let into our minds shapes how we think — poison in, poison out. Even after confession and forgiveness, real-world consequences (like the spread of gossip) may still linger, since forgiveness doesn't undo what was already shared with others. Not all \u201clawful\u201d knowledge is truly helpful or edifying (1 Corinthians 10:23) — a good filter for anything questionable we come across. Our father of confession is a safe guide because he places our salvation, above all else, at the center of his counsel.",
}

FLASH = {
1:[("Cross","Holds together enduring hardship and resurrection \u2014 suffering and victory together."),
   ("Hebrews 12:2","\u201cFor the joy set before Him, He endured the cross.\u201d"),
   ("Divine Dilemma","God loved humanity but had warned of the consequence of sin \u2014 resolved by mercy and truth meeting (Psalm 85:10)."),
   ("Why Christ had to be Creator","Only the Creator can recreate/renew a corrupted nature."),
   ("If God simply forgave sin","His justice would not stand.")],
2:[("Sign of the Cross, left to right","Symbolizes the Holy Spirit moving us from darkness to light."),
   ("1 Peter 2:24 & Hebrews 12:2 theme","Christ personally endured for us and died for us."),
   ("Galatians 3:13","Christ became a curse for us, taking our curse of death."),
   ("Spiritual death","Separation from God."),
   ("Mortal death","Subjection to a fallen, corrupt realm."),
   ("St. Athanasius on the Cross","Christ was lifted up to draw all people to Himself.")],
3:[("1700th anniversary (2026)","St. Helena's discovery of the True Cross (326 AD)."),
   ("Trial of Protection example","Abraham."),
   ("Acts 5:41","The apostles rejoiced to suffer shame for His name \u2014 joy from tribulation."),
   ("Litany of the Departed","Speaks of death as a step toward a realm with the saints.")],
4:[("Colosse today","Located in modern-day Turkey."),
   ("Who founded the Colossian church","Epaphras, not St. Paul."),
   ("Ephesians & Colossians in common","Both describe Christ as Head, and us as members of His Body."),
   ("What Epaphras reported to Paul","The Colossians' faith in Christ and love for the saints."),
   ("Why the gospel bore fruit in Colosse","They heard, experienced, and were transformed by the truth \u2014 not mere theory.")],
5:[("Gnosis","Greek for knowledge."),
   ("Praxis","Greek for action."),
   ("Gnostic belief","God is known through hidden knowledge, not Scripture, tradition, or doctrine."),
   ("John 14:26","The Holy Spirit teaches us all things."),
   ("Romans 8:26","The Holy Spirit intercedes for us when we don't know what to pray."),
   ("\u201cGod who created us without us...\u201d","Quote from St. Augustine \u2014 God saves us with our participation."),
   ("Philippians 2:12","Work out your own salvation \u2014 our synergy with God's grace.")],
6:[("Colossians 1:15","Christ is the image of the invisible God, the firstborn over all creation."),
   ("Ikon (Greek)","Image."),
   ("Firstborn (theological meaning)","Begotten of the Father, not created."),
   ("Colossians 1:16","All things were created through Him and for Him."),
   ("Potter and clay analogy","We are not our own masters, but God's servants.")],
7:[("Colossians 1:18","Christ is the firstborn from the dead \u2014 the first to rise and never die again."),
   ("Preeminence","As Creator, everything that exists belongs to Christ."),
   ("Romans 8:15","We received the Spirit of adoption into Christ's renewed Body."),
   ("St. Athanasius","\u201cGod became man so that man might become like god.\u201d"),
   ("Colossians 1:19","It pleased the Father that in Christ all the fullness should dwell."),
   ("The Eucharist","How we become sacramentally reconciled in the Body of His flesh.")],
8:[("Colossians 2:2-3","The mystery of God is Christ, in whom all treasures of wisdom and knowledge are hidden."),
   ("Colossians 3:14 (source of unity)","Love is the bond that holds everything together."),
   ("Fruit of the Spirit related here","Love (Galatians 5:22)."),
   ("\u201cWalk IN Him,\u201d not \u201cwith Him\u201d","Signifies real union, not mere companionship.")],
9:[("1 Corinthians 1:18-25 & Colossians 2:8-10","Worldly wisdom/tradition is foolish next to the Cross."),
   ("Judaizers","Insisted on strict Jewish legal tradition, even beyond God's own Law."),
   ("Circumcision (old covenant)","Foreshadowed spiritual circumcision of the heart through baptism."),
   ("Modern equivalent of ritual atonement laws","The sacrament of repentance and confession.")],
10:[("Colossians 2:14","The handwriting of debt against us was nailed to the Cross."),
    ("Colossians 2:13-14, 3 actions","Forgave trespasses, wiped out handwriting, nailed it to the Cross."),
    ("Colossians 2:16","Warns against Judaizers who judged others by food/festival laws."),
    ("Orthodox fasting purpose","A spiritual exercise of saying no to sin, not a claim food is evil.")],
11:[("Colossians 3:2","Set your mind on things above \u2014 stronger language than \u2018seek.\u2019"),
    ("Matthew 6:5-6 vs Matthew 23:5","Private, sincere devotion vs. public showiness."),
    ("Romans 8:13","The Spirit helps us put sinful \u2018members\u2019 to death."),
    ("Colossians 3:8, \u2018But now\u2019","Marks our chance to repent right now."),
    ("The Devil's signature move","Lie so we sin, then make us too guilty to repent.")],
12:[("Colossians 2:11 (step one)","Putting off the old self, before putting on the new."),
    ("Colossians 3:11","Christ is all, and in all \u2014 our old nature is past."),
    ("Meekness","Bearing wrong without retaliating \u2014 not weakness."),
    ("Colossians 3:14","Love is the bond of perfection, above all other virtues."),
    ("Colossians 3:15","Peace and thanksgiving are directly linked."),
    ("Colossians 3:16","Let the word of Christ dwell in you through psalms, hymns, spiritual songs.")],
13:[("Colossians 3:18-25 principle","Love and obedience are virtues for everyone, married or not."),
    ("Colossians 3:23-24","Whatever you do, do it heartily, as to the Lord \u2014 you serve Christ."),
    ("Colossians 3:21 (correct match)","Fathers, do not provoke your children, lest they become discouraged.")],
14:[("Colossians 4:2","Continue earnestly in prayer, being vigilant with thanksgiving."),
    ("Colossians 4:3","Praying for an open door to speak the mystery of Christ."),
    ("Intercession","Asking others to pray for us."),
    ("Colossians 4:5","Redeeming the time."),
    ("Philemon & Onesimus","\u2018Receive him... as a beloved brother\u2019 \u2014 becoming peacemakers through forgiveness."),
    ("\u2018Remember my chains\u2019","Co-suffering for Christ's sake as a path of growth.")],
15:[("John 3:14 / bronze serpent","Shows the Cross was God's plan from the beginning, not an accident."),
    ("Crucifixion","A Roman practice."),
    ("Psalm 85:10","Resolves the Divine Dilemma of God's love and justice."),
    ("A fitting Savior must be","Infinite, Holy, stronger than death, and the Creator."),
    ("2 Corinthians 5:21","He took what is ours and gave us what is His.")],
16:[("Bronze serpent & looking","Represents belief and synergistic cooperation with God."),
    ("No bones broken (Passover lamb)","Symbolizes the unbroken unity of Christ's Body, the Church."),
    ("Why Christ wasn't beheaded","As Head of the Body, beheading would symbolize separation from man."),
    ("St. Thomas","Best example of someone who wished for further explanation before believing."),
    ("Luke 9:23","\u2018Take up his cross daily, and follow Me.\u2019")],
17:[("St. John Chrysostom on Galatians 5:17","Virtue vs. wickedness truly oppose each other, not soul vs. body."),
    ("Asceticism","Disciplined spiritual exercise on the path to holiness \u2014 for everyone."),
    ("John 14:27","Christ's peace, unlike the peace the world gives."),
    ("Peace of Conscience example","The apostles rejoicing under persecution (Acts 5:41)."),
    ("God's peace described as","Coolness and repose.")],
18:[("Purity, defined","Guarding the sense of the heart to be united with our pure God."),
    ("European Ermine legend","Chooses purity over its very life."),
    ("Christ washing feet (John 13)","Ongoing repentance/confession restores union with Him."),
    ("2 Timothy 2:22","Flee youthful lusts \u2014 the element of escaping."),
    ("Metanoia (prostration)","Bury the sin as we go down, rise with Christ as we stand."),
    ("Money","A good servant but a bad master."),
    ("Philippians 4:11-13","Content in any circumstance, through Christ.")],
19:[("Why Eve fell","She treated the command as a superficial rule, not internalizing its significance."),
    ("Knowledge","A gift from God, meant to be cultivated for good."),
    ("Does the devil give knowledge?","Yes \u2014 either lies or malicious truths."),
    ("Purely academic pursuit apart from God","Tends to feed pride rather than draw us to God."),
    ("Knowing God's will","Not a literary pursuit, but a lived experience.")],
20:[("Matthew 6:33 principle","Investing in heavenly things lets God multiply our time."),
    ("Poison in, poison out","Whatever we let into our minds shapes our thinking."),
    ("Why consequences of gossip persist after confession","Harmful information already shared can't be un-transmitted."),
    ("1 Corinthians 10:23","Not all lawful things are helpful or edifying \u2014 a good test for questionable content."),
    ("Father of confession","A safe guide because he puts your salvation first.")],
}


# ---------------------------------------------------------------
# Study guide context (from the workbook's own 4-section topic
# outline). Each of the 4 sections below corresponds exactly to a
# contiguous Q-range shared by every day inside it, so it's attached
# per-day as shared context rather than guessed at question-level.
# ---------------------------------------------------------------
with open("study_guide_source.json", encoding="utf-8") as f:
    _SG = json.load(f)["study_guide"]["weeks"]

# (loQ, hiQ) -> which study-guide "week" (section) it maps to, 0-indexed
SECTION_RANGES = [(1, 15), (16, 70), (71, 116), (117, 194)]

def section_for(qlo, qhi):
    for i, (lo, hi) in enumerate(SECTION_RANGES):
        if qlo >= lo and qhi <= hi:
            return _SG[i]
    return None

def build_day(meta):
    day_num, week, weekday, bible, wrange, topic, time_est, qlo, qhi = meta
    quiz = []
    for q in Q:
        num, text, options, correct, expl = q
        if qlo <= num <= qhi:
            quiz.append({
                "num": num, "q": text, "options": options,
                "correct": correct if isinstance(correct, list) else [correct],
                "multi": isinstance(correct, list),
                "explain": expl
            })
    flash = [{"term": t, "def": d} for t, d in FLASH.get(day_num, [])]

    section = section_for(qlo, qhi)
    section_ctx = None
    if section:
        section_ctx = {
            "sectionTitle": section["title"],
            "objectives": section["objectives"],
            "topics": [{"title": t["title"], "summary": t["summary"]} for t in section["topics"]]
        }

    return {
        "day": day_num, "week": week, "weekday": weekday,
        "bible": bible, "workbookRange": wrange, "topic": topic, "time": time_est,
        "summary": LESSONS.get(day_num, ""),
        "flashcards": flash,
        "sectionContext": section_ctx,
        "quiz": quiz
    }

data = [build_day(m) for m in DAYS]

with open("data.js", "w") as f:
    f.write("// Auto-generated content data for the More Than Conquerors study app\n")
    f.write("const STUDY_DATA = ")
    f.write(json.dumps(data, indent=2, ensure_ascii=False))
    f.write(";\n")

print("Days:", len(data))
print("Total quiz Qs:", sum(len(d["quiz"]) for d in data))
print("Total flashcards:", sum(len(d["flashcards"]) for d in data))
